In [1]:
from PIL import Image
import numpy as np

https://www.pluralsight.com/guides/importing-image-data-into-numpy-arrays

https://stackoverflow.com/questions/62171840/how-to-resize-multiple-images-from-a-folder-convert-them-into-grayscale-and-sav

20 mil imagens positivas e 20 mil imagens negativas.

In [22]:
image = Image.open('../data/concrete_crack/Positive/04354.jpg')

In [23]:
# convert image to numpy array
data = np.asarray(image)
print(type(data))

<class 'numpy.ndarray'>


In [24]:
# summarize shape
print(data.shape)

(227, 227, 3)


In [25]:
image_path = '../data/concrete_crack/Positive/00001.jpg'
# o modo 'L' abaixo transforma a imagem em single channel
# interpretado, geralmente, como níveis de cinza
imagem = Image.open(image_path).convert('L').resize((32, 32))
imagem_array = np.array(imagem)
imagem_array.shape

(32, 32)

In [44]:
np.empty((1024,1)).ndim

2

In [38]:
imagem_array.flatten()

array([162, 160, 160, ..., 149, 146, 151], dtype=uint8)

In [52]:
np.empty((1, 1024))

array([[0.00000000e+000, 1.08646185e-311, 0.00000000e+000, ...,
                    nan,             nan,             nan]])

In [53]:
np.append(np.empty((1, 1024)), [imagem_array.flatten()], axis=0)

array([[0.00000000e+000, 1.00789392e-321, 0.00000000e+000, ...,
        9.04115219e+271, 3.05095282e-067, 9.29603063e+199],
       [1.62000000e+002, 1.60000000e+002, 1.60000000e+002, ...,
        1.49000000e+002, 1.46000000e+002, 1.51000000e+002]])

In [29]:
# import splitfolders

# splitfolders.ratio("../data/concrete_crack/",
#                    output="../data/concrete_crack_split/",
#                    seed=1337,
#                    ratio=(0.7, 0.3),
#                    move=False)

In [83]:
import os
import pandas as pd

data = pd.DataFrame()

matriz_positiva = np.empty((1, 1024))

path = "../data/concrete_crack/Positive"
lista_de_arquivos = os.listdir(path)
for imagem_original in lista_de_arquivos:
    imagem = Image.open(f"{path}/{imagem_original}").convert('L').resize((32, 32))
    imagem_array = np.array(imagem).flatten()
    matriz_positiva = np.append(matriz_positiva, [imagem_array], axis=0)
    
df = pd.DataFrame(matriz_positiva)
lista_de_arquivos.insert(0, 'teste')
df.insert(0, "arquivo", lista_de_arquivos)
df.insert(1, "classe", 1)

In [78]:
df = pd.DataFrame(matriz_positiva)
lista = os.listdir(path)
lista.insert(0, 'teste')
df.insert(0, "Arquivo", lista)

In [94]:
df_positivo

arquivo  classe      0      1      2      3      4      5      6  \
1      16679_1.jpg       1  170.0  174.0  177.0  172.0  167.0  161.0  156.0   
2        04354.jpg       1  183.0  186.0  191.0  187.0  178.0  179.0  182.0   
3        02725.jpg       1  158.0  158.0  160.0  149.0  149.0  157.0  155.0   
4      11369_1.jpg       1  187.0  187.0  190.0  192.0  196.0  195.0  201.0   
5        19463.jpg       1  176.0  174.0  174.0  162.0   71.0  166.0  206.0   
...            ...     ...    ...    ...    ...    ...    ...    ...    ...   
19996  18956_1.jpg       1  182.0  185.0  181.0  186.0  189.0  181.0  173.0   
19997    09669.jpg       1  205.0  206.0  213.0  192.0  147.0  205.0  213.0   
19998    05053.jpg       1  144.0  149.0  153.0  157.0  151.0  143.0  157.0   
19999    03422.jpg       1  186.0  186.0  188.0  188.0  188.0  185.0  182.0   
20000  12908_1.jpg       1  166.0  158.0  175.0  172.0  175.0  167.0  171.0   

           7  ...   1014   1015   1016   1017   1018   1019   1020   1021  \
1      161.0  ...  176.0  188.0  168.0   96.0   67.0   77.0  136.0  166.0   
2      181.0  ...  186.0  183.0  181.0  182.0  183.0  184.0  184.0  185.0   
3      150.0  ...  185.0  184.0  194.0  190.0  192.0  182.0  181.0  179.0   
4      216.0  ...  193.0  188.0  194.0  196.0  187.0  191.0  190.0  190.0   
5      170.0  ...  183.0  182.0  176.0  171.0  184.0  176.0  179.0  185.0   
...      ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
19996  174.0  ...  195.0  197.0  200.0  199.0  197.0  193.0  185.0  195.0   
19997  214.0  ...  204.0  201.0  206.0  207.0  201.0  202.0  200.0  202.0   
19998  157.0  ...  131.0  151.0  168.0  150.0  138.0  138.0  149.0  172.0   
19999  182.0  ...  183.0  180.0  181.0  181.0  184.0  186.0  166.0  166.0   
20000  164.0  ...   39.0   48.0   53.0   68.0  100.0  153.0  198.0  197.0   

        1022   1023  
1      175.0  171.0  
2      182.0  181.0  
3      198.0  190.0  
4      188.0  190.0  
5      174.0  190.0  
...      ...    ...  
19996  194.0  200.0  
19997  206.0  200.0  
19998  185.0  138.0  
19999  172.0  170.0  
20000  184.0  170.0  

[20000 rows x 1026 columns]

In [85]:
df_positivo = df.copy()

In [87]:
df_positivo = df_positivo.drop([0])

In [92]:
df_positivo.columns = df_positivo.columns.astype(str)

In [93]:
df_positivo.to_parquet("df_positivo.parquet", index=False)

In [95]:
teste = pd.read_parquet("df_positivo.parquet")
teste

arquivo  classe      0      1      2      3      4      5      6  \
0      16679_1.jpg       1  170.0  174.0  177.0  172.0  167.0  161.0  156.0   
1        04354.jpg       1  183.0  186.0  191.0  187.0  178.0  179.0  182.0   
2        02725.jpg       1  158.0  158.0  160.0  149.0  149.0  157.0  155.0   
3      11369_1.jpg       1  187.0  187.0  190.0  192.0  196.0  195.0  201.0   
4        19463.jpg       1  176.0  174.0  174.0  162.0   71.0  166.0  206.0   
...            ...     ...    ...    ...    ...    ...    ...    ...    ...   
19995  18956_1.jpg       1  182.0  185.0  181.0  186.0  189.0  181.0  173.0   
19996    09669.jpg       1  205.0  206.0  213.0  192.0  147.0  205.0  213.0   
19997    05053.jpg       1  144.0  149.0  153.0  157.0  151.0  143.0  157.0   
19998    03422.jpg       1  186.0  186.0  188.0  188.0  188.0  185.0  182.0   
19999  12908_1.jpg       1  166.0  158.0  175.0  172.0  175.0  167.0  171.0   

           7  ...   1014   1015   1016   1017   1018   1019   1020   1021  \
0      161.0  ...  176.0  188.0  168.0   96.0   67.0   77.0  136.0  166.0   
1      181.0  ...  186.0  183.0  181.0  182.0  183.0  184.0  184.0  185.0   
2      150.0  ...  185.0  184.0  194.0  190.0  192.0  182.0  181.0  179.0   
3      216.0  ...  193.0  188.0  194.0  196.0  187.0  191.0  190.0  190.0   
4      170.0  ...  183.0  182.0  176.0  171.0  184.0  176.0  179.0  185.0   
...      ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
19995  174.0  ...  195.0  197.0  200.0  199.0  197.0  193.0  185.0  195.0   
19996  214.0  ...  204.0  201.0  206.0  207.0  201.0  202.0  200.0  202.0   
19997  157.0  ...  131.0  151.0  168.0  150.0  138.0  138.0  149.0  172.0   
19998  182.0  ...  183.0  180.0  181.0  181.0  184.0  186.0  166.0  166.0   
19999  164.0  ...   39.0   48.0   53.0   68.0  100.0  153.0  198.0  197.0   

        1022   1023  
0      175.0  171.0  
1      182.0  181.0  
2      198.0  190.0  
3      188.0  190.0  
4      174.0  190.0  
...      ...    ...  
19995  194.0  200.0  
19996  206.0  200.0  
19997  185.0  138.0  
19998  172.0  170.0  
19999  184.0  170.0  

[20000 rows x 1026 columns]

In [96]:
import os
import pandas as pd

data = pd.DataFrame()

matriz_positiva = np.empty((1, 1024))

path = "../data/concrete_crack/Negative"
lista_de_arquivos = os.listdir(path)
for imagem_original in lista_de_arquivos:
    imagem = Image.open(f"{path}/{imagem_original}").convert('L').resize((32, 32))
    imagem_array = np.array(imagem).flatten()
    matriz_positiva = np.append(matriz_positiva, [imagem_array], axis=0)
    
df = pd.DataFrame(matriz_positiva)
lista_de_arquivos.insert(0, 'teste')
df.insert(0, "arquivo", lista_de_arquivos)
df.insert(1, "classe", 0)

In [97]:
df_negativo = df.copy()

In [100]:
df_negativo = df_negativo.drop(columns=['classe'])

In [101]:
df_negativo.insert(1, "classe", 0)

In [102]:
df_negativo

arquivo  classe      0              1      2              3  \
0          teste       0    0.0  6.944939e-310    0.0  6.944939e-310   
1      14147.jpg       0  181.0   1.970000e+02  205.0   2.080000e+02   
2      04354.jpg       0  197.0   1.770000e+02  173.0   1.540000e+02   
3      13628.jpg       0  194.0   2.010000e+02  204.0   2.020000e+02   
4      12536.jpg       0  190.0   1.930000e+02  189.0   1.950000e+02   
...          ...     ...    ...            ...    ...            ...   
19996  11026.jpg       0  166.0   1.720000e+02  183.0   1.740000e+02   
19997  05053.jpg       0  175.0   1.720000e+02  175.0   1.720000e+02   
19998  15240.jpg       0  161.0   1.610000e+02  162.0   1.610000e+02   
19999  03422.jpg       0  213.0   2.120000e+02  202.0   2.060000e+02   
20000  13631.jpg       0  163.0   1.810000e+02  184.0   1.820000e+02   

                   4              5              6              7  ...  \
0      6.944868e-310  6.944939e-310  7.410985e-323  6.944939e-310  ...   
1       2.030000e+02   2.040000e+02   2.020000e+02   2.010000e+02  ...   
2       1.770000e+02   1.780000e+02   1.730000e+02   1.870000e+02  ...   
3       1.980000e+02   1.920000e+02   1.940000e+02   1.960000e+02  ...   
4       1.980000e+02   1.950000e+02   1.920000e+02   1.940000e+02  ...   
...              ...            ...            ...            ...  ...   
19996   1.420000e+02   1.530000e+02   1.440000e+02   1.610000e+02  ...   
19997   1.700000e+02   1.700000e+02   1.660000e+02   1.640000e+02  ...   
19998   1.630000e+02   1.610000e+02   1.620000e+02   1.620000e+02  ...   
19999   2.090000e+02   2.070000e+02   2.080000e+02   2.070000e+02  ...   
20000   1.860000e+02   1.950000e+02   1.830000e+02   1.830000e+02  ...   

                1014           1015           1016           1017  \
0      2.137868e-314  2.137868e-314  2.137868e-314  2.137958e-314   
1       2.000000e+02   2.010000e+02   2.000000e+02   2.020000e+02   
2       1.980000e+02   1.970000e+02   1.950000e+02   1.990000e+02   
3       1.990000e+02   2.000000e+02   1.990000e+02   1.950000e+02   
4       1.890000e+02   1.920000e+02   1.930000e+02   1.960000e+02   
...              ...            ...            ...            ...   
19996   1.940000e+02   1.920000e+02   1.870000e+02   1.890000e+02   
19997   1.670000e+02   1.700000e+02   1.760000e+02   1.710000e+02   
19998   1.640000e+02   1.640000e+02   1.640000e+02   1.650000e+02   
19999   2.060000e+02   2.020000e+02   2.150000e+02   2.300000e+02   
20000   1.930000e+02   1.850000e+02   1.800000e+02   1.820000e+02   

                1018           1019           1020           1021  \
0      2.137868e-314  2.137868e-314  2.138425e-314  2.363008e-314   
1       1.980000e+02   2.030000e+02   2.010000e+02   2.020000e+02   
2       2.020000e+02   1.930000e+02   1.970000e+02   2.040000e+02   
3       2.010000e+02   2.000000e+02   2.020000e+02   2.050000e+02   
4       1.910000e+02   1.860000e+02   1.920000e+02   1.860000e+02   
...              ...            ...            ...            ...   
19996   1.880000e+02   1.840000e+02   1.970000e+02   1.870000e+02   
19997   1.680000e+02   1.690000e+02   1.680000e+02   1.700000e+02   
19998   1.630000e+02   1.630000e+02   1.660000e+02   1.640000e+02   
19999   2.050000e+02   1.920000e+02   1.890000e+02   1.930000e+02   
20000   1.880000e+02   1.720000e+02   1.830000e+02   1.880000e+02   

                1022           1023  
0      2.173403e-314  2.138426e-314  
1       1.950000e+02   2.030000e+02  
2       2.010000e+02   2.020000e+02  
3       2.060000e+02   2.080000e+02  
4       1.820000e+02   2.090000e+02  
...              ...            ...  
19996   1.870000e+02   1.910000e+02  
19997   1.710000e+02   1.640000e+02  
19998   1.630000e+02   1.610000e+02  
19999   1.880000e+02   1.890000e+02  
20000   1.800000e+02   1.870000e+02  

[20001 rows x 1026 columns]

In [104]:
df_negativo = df_negativo.drop([0])

In [105]:
df_negativo.columns = df_negativo.columns.astype(str)

In [106]:
df_negativo

arquivo  classe      0      1      2      3      4      5      6  \
1      14147.jpg       0  181.0  197.0  205.0  208.0  203.0  204.0  202.0   
2      04354.jpg       0  197.0  177.0  173.0  154.0  177.0  178.0  173.0   
3      13628.jpg       0  194.0  201.0  204.0  202.0  198.0  192.0  194.0   
4      12536.jpg       0  190.0  193.0  189.0  195.0  198.0  195.0  192.0   
5      15259.jpg       0  204.0  208.0  206.0  207.0  205.0  207.0  207.0   
...          ...     ...    ...    ...    ...    ...    ...    ...    ...   
19996  11026.jpg       0  166.0  172.0  183.0  174.0  142.0  153.0  144.0   
19997  05053.jpg       0  175.0  172.0  175.0  172.0  170.0  170.0  166.0   
19998  15240.jpg       0  161.0  161.0  162.0  161.0  163.0  161.0  162.0   
19999  03422.jpg       0  213.0  212.0  202.0  206.0  209.0  207.0  208.0   
20000  13631.jpg       0  163.0  181.0  184.0  182.0  186.0  195.0  183.0   

           7  ...   1014   1015   1016   1017   1018   1019   1020   1021  \
1      201.0  ...  200.0  201.0  200.0  202.0  198.0  203.0  201.0  202.0   
2      187.0  ...  198.0  197.0  195.0  199.0  202.0  193.0  197.0  204.0   
3      196.0  ...  199.0  200.0  199.0  195.0  201.0  200.0  202.0  205.0   
4      194.0  ...  189.0  192.0  193.0  196.0  191.0  186.0  192.0  186.0   
5      204.0  ...  204.0  202.0  203.0  202.0  203.0  208.0  209.0  207.0   
...      ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
19996  161.0  ...  194.0  192.0  187.0  189.0  188.0  184.0  197.0  187.0   
19997  164.0  ...  167.0  170.0  176.0  171.0  168.0  169.0  168.0  170.0   
19998  162.0  ...  164.0  164.0  164.0  165.0  163.0  163.0  166.0  164.0   
19999  207.0  ...  206.0  202.0  215.0  230.0  205.0  192.0  189.0  193.0   
20000  183.0  ...  193.0  185.0  180.0  182.0  188.0  172.0  183.0  188.0   

        1022   1023  
1      195.0  203.0  
2      201.0  202.0  
3      206.0  208.0  
4      182.0  209.0  
5      208.0  207.0  
...      ...    ...  
19996  187.0  191.0  
19997  171.0  164.0  
19998  163.0  161.0  
19999  188.0  189.0  
20000  180.0  187.0  

[20000 rows x 1026 columns]

In [107]:
df_negativo.to_parquet("df_negativo.parquet", index=False)

In [109]:
df_total = pd.concat([df_positivo, df_negativo])

In [110]:
df_total.to_parquet("df_total.parquet", index=False)