# Fundamentos de Análise de Dados 2022.1

# Dataset

_Naval Propulsion Plants_: regressão múltipla (2 variáveis de saída), estimar cada variável de saída separadamente:
- 11934 amostras;
- 16 características reais;
- 2 características reais para estimar, mas estimar somente _GT Compressor decay state coecient_ (remover _GT Turbine decay state coecient_).

# 01. Fazer o _download_ do respectivo banco de dados.

Link: http://archive.ics.uci.edu/ml/datasets/condition+based+maintenance+of+naval+propulsion+plants

Após feito o download, os dados foram salvos em _"../data/naval_data.txt"_.

# 02. Fazer a leitura dos dados.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
features = [
    "Lever position",
    "Ship speed",
    "Gas Turbine shaft torque",
    "GT rate of revolutions",
    "Gas Generator rate of revolutions",
    "Starboard Propeller Torque",
    "Port Propeller Torque",
    "Hight Pressure Turbine exit temperature",
    "GT Compressor inlet air temperature",
    "GT Compressor outlet air temperature",
    "HP Turbine exit pressure",
    "GT Compressor inlet air pressure",
    "GT Compressor outlet air pressure",
    "GT exhaust gas pressure",
    "Turbine Injecton Control",
    "Fuel flow",
    "GT Compressor decay state coefficient",
    "GT Turbine decay state coefficient"
]

In [3]:
# read data using read_csv
# raw_data = pd.read_csv("data/naval_data.txt", sep="   ", header=None, engine='python')

# read data using read_fwf
raw_data = pd.read_fwf("data/naval_data.txt", header=None)
raw_data.columns = features

In [4]:
raw_data.head()

Lever position  Ship speed  Gas Turbine shaft torque  \
0           1.138         3.0                   289.964   
1           2.088         6.0                  6960.180   
2           3.144         9.0                  8379.229   
3           4.161        12.0                 14724.395   
4           5.140        15.0                 21636.432   

   GT rate of revolutions  Gas Generator rate of revolutions  \
0                1349.489                           6677.380   
1                1376.166                           6828.469   
2                1386.757                           7111.811   
3                1547.465                           7792.630   
4                1924.313                           8494.777   

   Starboard Propeller Torque  Port Propeller Torque  \
0                       7.584                  7.584   
1                      28.204                 28.204   
2                      60.358                 60.358   
3                     113.774                113.774   
4                     175.306                175.306   

   Hight Pressure Turbine exit temperature  \
0                                  464.006   
1                                  635.401   
2                                  606.002   
3                                  661.471   
4                                  731.494   

   GT Compressor inlet air temperature  GT Compressor outlet air temperature  \
0                                288.0                               550.563   
1                                288.0                               581.658   
2                                288.0                               587.587   
3                                288.0                               613.851   
4                                288.0                               645.642   

   HP Turbine exit pressure  GT Compressor inlet air pressure  \
0                     1.096                             0.998   
1                     1.331                             0.998   
2                     1.389                             0.998   
3                     1.658                             0.998   
4                     2.078                             0.998   

   GT Compressor outlet air pressure  GT exhaust gas pressure  \
0                              5.947                    1.019   
1                              7.282                    1.019   
2                              7.574                    1.020   
3                              9.007                    1.022   
4                             11.197                    1.026   

   Turbine Injecton Control  Fuel flow  GT Compressor decay state coefficient  \
0                     7.137      0.082                                   0.95   
1                    10.655      0.287                                   0.95   
2                    13.086      0.259                                   0.95   
3                    18.109      0.358                                   0.95   
4                    26.373      0.522                                   0.95   

   GT Turbine decay state coefficient  
0                               0.975  
1                               0.975  
2                               0.975  
3                               0.975  
4                               0.975

In [5]:
# convert the DataFrame into a Numpy array
naval_array = raw_data.to_numpy()
naval_array

array([[1.1380000e+00, 3.0000000e+00, 2.8996400e+02, ..., 8.2000000e-02,
        9.5000000e-01, 9.7500000e-01],
       [2.0880000e+00, 6.0000000e+00, 6.9601800e+03, ..., 2.8700000e-01,
        9.5000000e-01, 9.7500000e-01],
       [3.1440000e+00, 9.0000000e+00, 8.3792290e+03, ..., 2.5900000e-01,
        9.5000000e-01, 9.7500000e-01],
       ...,
       [7.1480000e+00, 2.1000000e+01, 3.9003867e+04, ..., 8.3400000e-01,
        1.0000000e+00, 1.0000000e+00],
       [8.2060000e+00, 2.4000000e+01, 5.0992579e+04, ..., 1.1490000e+00,
        1.0000000e+00, 1.0000000e+00],
       [9.3000000e+00, 2.7000000e+01, 7.2775130e+04, ..., 1.7040000e+00,
        1.0000000e+00, 1.0000000e+00]])

# 03. Se necessário, dividir os dados em conjunto de treinamento (70%) e teste (30%), utilizando a função apropriada do scikit-learn. Quatro NumPy arrays devem ser criados: X_train, y_train, X_test e y_test.

In [6]:
data = raw_data.copy()

X = data.drop(["GT Compressor decay state coefficient",
               "GT Turbine decay state coefficient"],
              axis=1)

y = data[["GT Compressor decay state coefficient"]]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12)

In [8]:
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

# 04. Acrescentar uma coluna de 1s ([1 1 . . . 1]^T) como última coluna da matriz de treinamento Xtrain (vamos chamá-la de X_train_2). Repita o procedimento para a matriz de teste, chamando-a de X_test_2.

[StackOverflow: How to add an extra column to a NumPy array](https://stackoverflow.com/questions/8486294/how-to-add-an-extra-column-to-a-numpy-array)

In [9]:
X_train.shape

(8353, 16)

In [10]:
X_train_2 = np.c_[X_train, np.ones(8353)]
X_train_2

array([[1.1380000e+00, 3.0000000e+00, 3.2824350e+03, ..., 3.2952000e+01,
        2.2300000e-01, 1.0000000e+00],
       [1.1380000e+00, 3.0000000e+00, 1.1174930e+03, ..., 0.0000000e+00,
        8.8000000e-02, 1.0000000e+00],
       [5.1400000e+00, 1.5000000e+01, 2.1622291e+04, ..., 2.4760000e+01,
        4.9000000e-01, 1.0000000e+00],
       ...,
       [5.1400000e+00, 1.5000000e+01, 2.1632784e+04, ..., 2.5752000e+01,
        5.1000000e-01, 1.0000000e+00],
       [4.1610000e+00, 1.2000000e+01, 1.4717766e+04, ..., 1.7318000e+01,
        3.4300000e-01, 1.0000000e+00],
       [1.1380000e+00, 3.0000000e+00, 4.8720200e+03, ..., 0.0000000e+00,
        2.1600000e-01, 1.0000000e+00]])

In [11]:
X_test.shape

(3581, 16)

In [12]:
X_test_2 = np.c_[X_test, np.ones(3581)]
X_test_2

array([[8.2060000e+00, 2.4000000e+01, 5.0993295e+04, ..., 5.8804000e+01,
        1.1640000e+00, 1.0000000e+00],
       [7.1480000e+00, 2.1000000e+01, 3.8998174e+04, ..., 4.3301000e+01,
        8.5700000e-01, 1.0000000e+00],
       [4.1610000e+00, 1.2000000e+01, 1.4721227e+04, ..., 1.6673000e+01,
        3.3000000e-01, 1.0000000e+00],
       ...,
       [2.0880000e+00, 6.0000000e+00, 4.6389390e+03, ..., 2.3683000e+01,
        2.2200000e-01, 1.0000000e+00],
       [8.2060000e+00, 2.4000000e+01, 5.0992731e+04, ..., 5.8350000e+01,
        1.1550000e+00, 1.0000000e+00],
       [1.1380000e+00, 3.0000000e+00, 5.0947110e+03, ..., 1.2657000e+01,
        2.4200000e-01, 1.0000000e+00]])

# 05. Calcular o posto das matrizes X_train_2 e X_test_2. Se necessário, ajustar as matrizes X_train_2 e X_test_2.

In [13]:
np.linalg.matrix_rank(X_train_2)

14

In [14]:
np.linalg.matrix_rank(X_test_2)

14

# 06. Calcular a decomposição QR da matriz de treinamento: X_train_2 = QR, usando a função do NumPy apropriada.

In [16]:
q, r = np.linalg.qr(X_train_2)

# 07. Calcular o vetor de coeficientes $\tilde{x}$  da Equação (1), utilizando a função do NumPy linalg.solve.

## Regressão: O Método dos Mínimos Quadrados

O Método dos Mínimos Quadrados consiste em encontrar uma solução aproximada, $\tilde{x}$ , de um sistema linear inconsistente

$Ax = b$.

Isso é feito projetando o vetor b no espaço-nulo esquerdo de A e resolvendo as equações normais

$A^TA\tilde{x} = A^Tb$.

Pode-se substituir A por sua decomposição QR, A = QR, e obter novas equações normais:

$R\tilde{x} = Q^Tb$, (1)

sob determinadas condições em A.

In [19]:
# np.linalg.solve(a, b)